"use strict";
exports.__esModule = true;
var Stack_1 = require("./lib/Stack");
var stack = new Stack_1["default"]();
stack.push('一');
stack.push('二');
stack.push('三');
stack.pop();
console.log(stack.peek());
console.log(stack.size());
console.log(stack.isEmpty());
console.log(stack.toString());
